---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-lb-{{ (datasource "data").customerName }}
  namespace: lbns
spec:
  selector:
    istio: ingressgateway-lb
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ strings.Quote (datasource "data").istioHosts }}
    - {{ strings.Quote (datasource "data").domainName }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - {{ strings.Quote (datasource "data").istioHosts }}
    - {{ strings.Quote (datasource "data").domainName }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: lbns
  name: vs-lb-{{ (datasource "data").customerName }}
spec:
  hosts:
  - {{ strings.Quote (datasource "data").istioHosts }}
  - {{ strings.Quote (datasource "data").domainName }}
  gateways:
  - gateway-lb-{{ (datasource "data").customerName }}
  http:
  - route:
    - destination:
        host: istio-ingressgateway-{{ (datasource "data").customerName }}.{{ (datasource "data").namespace }}.svc.cluster.local
        port:
          number: 80
  tls:
  - match:
    - port: 443
      sniHosts:
      - {{ strings.Quote (datasource "data").istioHosts }}
      - {{ strings.Quote (datasource "data").domainName }}
    route:
    - destination:
        host: istio-ingressgateway-{{ (datasource "data").customerName }}.{{ (datasource "data").namespace }}.svc.cluster.local
        port:
          number: 443

