---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: request-keycloak-auth
  namespace: {{ (datasource "data").namespace }}
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: {{ strings.Quote (datasource "data").oidcIssuerUrl }}
    jwksUri: {{ strings.Quote (datasource "data").jwksUri }}
